services:
  web:
    image: fossology/fossology:4.4.0
    container_name: fossology-web
    restart: always
    depends_on:
      - db
    environment:
      FOSSOLOGY_DB_HOST: db
      FOSSOLOGY_DB_PORT: 5432
      FOSSOLOGY_DB_NAME: fossology
      FOSSOLOGY_DB_USER: fossy
      FOSSOLOGY_DB_PASSWORD: fossy-pass
    ports:
      - "8081:80"
    volumes:
      - ./volumes/fossology:/var/lib/fossology

  db:
    image: postgres:15
    container_name: fossology-db
    restart: always
    environment:
      POSTGRES_DB: fossology
      POSTGRES_USER: fossy
      POSTGRES_PASSWORD: fossy-pass
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
